version: "3.9"

services:
  nodejs:
    image: makegood-nodejs:latest
    ports:
      - 3000:3000

  nginx:
    image: makeggod-nginx
    ports:
      - 80:80
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

