version: "3.9"

services:
  certbot:
    image: makegood-certbot:latest
    command: certonly --agree-tos -m klimenkomaximsergievich@gmail.com  --dns-route53 --domains makegood.mksplayground.online
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  nodejs:
    image: makegood-nodejs:latest
    ports:
      - 3000:3000

  nginx:
    image: makeggod-nginx:latest
    ports:
      - 443:443
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - certbot


