version: "3.9"

services:
  nodejs:
    image: makegood-nodejs:latest
    ports:
      - 3000:3000

  nginx:
    image: makeggod-nginx:latest
    ports:
      - 443:443
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

